In [1]:
import io

import pandas as pd
from Bio import Entrez, SeqIO
from mysql.connector import connection
from sshtunnel import SSHTunnelForwarder

# Укажите ваш email (обязательно для использования Entrez)
Entrez.email = "your.email@example.com"

In [2]:
with open("db_curated_server_info.txt", "r") as file:
    lines = file.readlines()

config = {}

for line in lines:
    line = line.strip()
    if line and not line.startswith("#"):
        key, value = line.split("=", 1)
        config[key] = value.strip()

server_name = config.get("server_name")
srever_port = int(config.get("srever_port"))
ssh_password = config.get("ssh_password")
ssh_username = config.get("ssh_username")
db_adress = config.get("db_adress")
db_port = int(config.get("db_port"))

In [3]:
tunnel = SSHTunnelForwarder(
    (server_name, srever_port),
    ssh_password=ssh_password,
    ssh_username=ssh_username,
    remote_bind_address=(db_adress, db_port),
)
tunnel.start()
print(tunnel.local_bind_port)

34487

In [4]:
conn = connection.MySQLConnection(
    user="db_user",
    password="db_password",
    host="localhost",
    port=tunnel.local_bind_port,
    database="db_name",
)
cursor = conn.cursor()

In [5]:
query = "SHOW TABLES;"
cursor.execute(query)
cursor.fetchall()

[('alternative_name',),
 ('histone',),
 ('histone_description',),
 ('histone_has_publication',),
 ('publication',),
 ('sequence',),
 ('sequence_has_publication',)]

In [27]:
add_histone = (
    "INSERT INTO histone "
    "(id, level, taxonomic_span, taxonomic_span_id, description, parent) "
    "VALUES (%(id)s, %(level)s, %(taxonomic_span)s, %(taxonomic_span_id)s, %(description)s, %(parent)s)"
)
# add_histone_description = (
#     "INSERT INTO histone_description "
#     "(summary, taxonomy, genes, evolution, expression, knock_out, function, sequence, localization, deposition, structure, interactions, disease, caveats) "
#     "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
# )
# add_publication = (
#     "INSERT INTO publication "
#     "(id, title, doi, author, year) "
#     "VALUES (%(id)s, %(title)s, %(doi)s, %(author)s, %(year)s)"
# )
# add_sequence = (
#     "INSERT INTO sequence "
#     "(accession, variant, gi, ncbi_gene_id, hgnc_gene_name, taxonomy_id, organism, phylum, class, taxonomy_group, info, sequence, variant_under_consideration) "
#     "VALUES (%(accession)s, %(variant)s, %(gi)s, %(ncbi_gene_id)s, %(hgnc_gene_name)s, %(taxonomy_id)s, %(organism)s, %(phylum)s, %(class)s, %(taxonomy_group)s, %(info)s, %(sequence)s, %(variant_under_consideration)s)"
# )
# add_sequence_has_publication = (
#     "INSERT INTO sequence_has_publication "
#     "(sequence_accession, publication_id) "
#     "VALUES (%s, %s)"
# )
# add_alternate_names = (
#     "INSERT INTO alternative_name "
#     "(name, taxonomy, gene, splice, histone) "
#     "VALUES (%(name)s, %(taxonomy)s, %(gene)s, %(splice)s, %(histone)s)"
# )
# add_histone_has_publication = (
#     "INSERT INTO histone_has_publication "
#     "(histone_id, publication_id) "
#     "VALUES (%s, %s)"
# )

# To Do H3

## <span style="color:green">Correct sequence class of HISTDB_H3_V_Trypanosomatidae_1 (delete first space)</span>

## <span style="color:green">Change sequence variant of cH3s</span>

```python
[{'accession': 'CAA32434.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_001027285.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_001044904.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'NP_001050276.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'NP_001091119.1',
  'variant': 'cH3_(Vertebrata)'},
 {'accession': 'NP_001180643.1',
  'variant': 'cH3.1_(Mammalia)'},
 {'accession': 'NP_001268409.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_189372.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'NP_509344.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_659539.1',
  'variant': 'cH3.1_(Mammalia)'},
 {'accession': 'XP_001016594.3',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_001218942.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_002288694.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_002788889.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_002977792.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'XP_002999294.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_460476.1',
  'variant': 'cH3_(Fungi)'},
 {'accession': 'XP_527254.2',
  'variant': 'cH3.1_(Mammalia)'},
 {'accession': 'XP_719887.1',
  'variant': 'cH3_(Fungi)'},
 {'accession': 'XP_724814.1',
  'variant': 'cH3_(Protists)'}]
```

# To Do H4

## <span style="color:green">Change sequence variant of cH4s</span>

```python
[{'accession': 'NP_001027352.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_001032934.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_001087926.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_001131585.1',
  'variant': 'cH4_(Embryophyta)'},
 {'accession': 'NP_009563.1',
  'variant': 'cH4_(Fungi)'},
 {'accession': 'NP_180441.1',
  'variant': 'cH4_(Embryophyta)'},
 {'accession': 'NP_291074.1',
  'variant': 'cH4_(Mammalia)'},
 {'accession': 'NP_492641.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_999707.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'XP_001016593.1',
  'variant': 'cH4_(Protists)'},
 {'accession': 'XP_012928609.1',
  'variant': 'cH4_(Mammalia)'},
 {'accession': 'XP_951561.1',
  'variant': 'cH4_(Protists)'}]
```

# DONE H3

## <span style="color:black">Correct sequence class of HISTDB_H3_V_Trypanosomatidae_1 (delete first space)</span>

In [8]:
query = "SELECT * FROM sequence WHERE accession='HISTDB_H3_V_Trypanosomatidae_1'"
cursor.execute(query)
df = pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])
df

,accession,variant,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,sequence,variant_under_consideration
0,HISTDB_H3_V_Trypanosomatidae_1,H3.V_(Trypanosomatidae),None,None,None,5664,Leishmania major,Euglenozoa,Kinetoplastea,None,None,MAGITKAAVVASHPKKNVASRKMNKKSRSIAKKEAKAMRADSAGAK...,None

In [9]:
df["class"].values[0]

' Kinetoplastea'

In [10]:
query = "UPDATE sequence SET class='Kinetoplastea' WHERE accession='HISTDB_H3_V_Trypanosomatidae_1'"
cursor.execute(query)

In [11]:
query = "SELECT * FROM sequence WHERE accession='HISTDB_H3_V_Trypanosomatidae_1'"
cursor.execute(query)
pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])[
    "class"
].values[0]

'Kinetoplastea'

In [12]:
# Make sure data is committed to the database
conn.commit()

## <span style="color:black">Change sequence variant of cH3s</span>

```python
[{'accession': 'CAA32434.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_001027285.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_001044904.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'NP_001050276.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'NP_001091119.1',
  'variant': 'cH3_(Vertebrata)'},
 {'accession': 'NP_001180643.1',
  'variant': 'cH3.1_(Mammalia)'},
 {'accession': 'NP_001268409.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_189372.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'NP_509344.1',
  'variant': 'cH3_(Animals)'},
 {'accession': 'NP_659539.1',
  'variant': 'cH3.1_(Mammalia)'},
 {'accession': 'XP_001016594.3',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_001218942.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_002288694.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_002788889.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_002977792.1',
  'variant': 'cH3_(Embryophyta)'},
 {'accession': 'XP_002999294.1',
  'variant': 'cH3_(Protists)'},
 {'accession': 'XP_460476.1',
  'variant': 'cH3_(Fungi)'},
 {'accession': 'XP_527254.2',
  'variant': 'cH3.1_(Mammalia)'},
 {'accession': 'XP_719887.1',
  'variant': 'cH3_(Fungi)'},
 {'accession': 'XP_724814.1',
  'variant': 'cH3_(Protists)'}]
```

In [14]:
data_for_upd = {
    "CAA32434.1": "cH3_(Animals)",
    "NP_001027285.1": "cH3_(Animals)",
    "NP_001044904.1": "cH3_(Embryophyta)",
    "NP_001050276.1": "cH3_(Embryophyta)",
    "NP_001091119.1": "cH3_(Vertebrata)",
    "NP_001180643.1": "cH3.1_(Mammalia)",
    "NP_001268409.1": "cH3_(Animals)",
    "NP_189372.1": "cH3_(Embryophyta)",
    "NP_509344.1": "cH3_(Animals)",
    "NP_659539.1": "cH3.1_(Mammalia)",
    "XP_001016594.3": "cH3_(Protists)",
    "XP_001218942.1": "cH3_(Protists)",
    "XP_002288694.1": "cH3_(Protists)",
    "XP_002788889.1": "cH3_(Protists)",
    "XP_002977792.1": "cH3_(Embryophyta)",
    "XP_002999294.1": "cH3_(Protists)",
    "XP_460476.1": "cH3_(Fungi)",
    "XP_527254.2": "cH3.1_(Mammalia)",
    "XP_719887.1": "cH3_(Fungi)",
    "XP_724814.1": "cH3_(Protists)",
}
len(data_for_upd.keys())

20

In [16]:
query = "SELECT * FROM sequence "
cursor.execute(query)
df = pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])
print(df[df["accession"].isin(data_for_upd.keys())].shape)
df[df["accession"].isin(data_for_upd.keys())]

(20, 13)

,accession,variant,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,sequence,variant_under_consideration
942,CAA32434.1,cH3,8070,None,None,7227.0,Drosophila melanogaster,Arthropoda,Insecta,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3411,NP_001027285.1,cH3,78706960,None,None,7227.0,Drosophila melanogaster,Arthropoda,Insecta,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3421,NP_001044904.1,cH3,115441249,None,None,39947.0,Oryza sativa Japonica Group,Streptophyta,Magnoliopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRFRPGT...,None
3422,NP_001050276.1,cH3,115453351,None,None,39947.0,Oryza sativa Japonica Group,Streptophyta,Magnoliopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...,None
3439,NP_001091119.1,cH3,148234575,None,None,8355.0,Xenopus laevis,Chordata,Amphibia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3454,NP_001180643.1,cH3,302565464,None,None,9544.0,Macaca mulatta,Chordata,Mammalia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3465,NP_001268409.1,cH3,527498246,None,None,9031.0,Gallus gallus,Chordata,Aves,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3586,NP_189372.1,cH3,15232146,None,None,3702.0,Arabidopsis thaliana,Streptophyta,Magnoliopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRFRPGT...,None
3603,NP_509344.1,cH3,17567723,None,None,6239.0,Caenorhabditis elegans,Nematoda,Chromadorea,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...,None
3620,NP_659539.1,cH3,21489955,None,None,10090.0,Mus musculus,Chordata,Mammalia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5714,XP_001016594.3,cH3,229595561,None,None,312017.0,Tetrahymena thermophila SB210,Ciliophora,Oligohymenophorea,None,None,MARTKQTARKSTGAKAPRKQLASKAARKSAPATGGIKKPHRFRPGT...,None
5719,XP_001218942.1,cH3,115504299,None,None,185431.0,Trypanosoma brucei brucei TREU927,Euglenozoa,Kinetoplastea,None,None,MSRTKETARTKKTITSKKSKKASKGSDAASGVKTAQRRWRPGTVAL...,None
5755,XP_002288694.1,cH3,223998042,None,None,296543.0,Thalassiosira pseudonana CCMP1335,Bacillariophyta,Coscinodiscophyceae,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5775,XP_002788889.1,cH3,294956322,None,None,423536.0,Perkinsus marinus ATCC 50983,Perkinsozoa,None,None,None,MARTKQTARKSTGGKAPRKQLASKAARKSTPSTGGIKKPHRYRPGT...,None
5794,XP_002977792.1,cH3,302792052,None,None,88036.0,Selaginella moellendorffii,Streptophyta,Lycopodiopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...,None
5795,XP_002999294.1,cH3,301115049,None,None,403677.0,Phytophthora infestans T30-4,Oomycota,None,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5920,XP_460476.1,cH3,50423783,None,None,284592.0,Debaryomyces hansenii CBS767,Ascomycota,Saccharomycetes,None,None,MARTKQTARKSTGGKAPRKQLASKAARKSAPVSGGVKKPHRYKPGT...,None
5921,XP_527254.2,cH3,114605759,None,None,9598.0,Pan troglodytes,Chordata,Mammalia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5934,XP_719887.1,cH3,68472183,None,None,237561.0,Candida albicans SC5314,Ascomycota,Saccharomycetes,None,None,MARTKQTARKSTGGKAPRKQLASKAARKSAPVSGGVKKPHRYKPGT...,None
5935,XP_724814.1,cH3,82541094,None,None,5861.0,Plasmodium yoelii,Apicomplexa,Aconoidasida,None,None,MARTKQTARKSTAGKAPRKQLASKAARKSAPISAGIKKPHRYRPGT...,None

In [18]:
for a, v in data_for_upd.items():
    query = f"UPDATE sequence SET variant='{v}' WHERE accession='{a}'"
    cursor.execute(query)
    print(query)

UPDATE sequence SET variant='cH3_(Animals)' WHERE accession='CAA32434.1'
UPDATE sequence SET variant='cH3_(Animals)' WHERE accession='NP_001027285.1'
UPDATE sequence SET variant='cH3_(Embryophyta)' WHERE accession='NP_001044904.1'
UPDATE sequence SET variant='cH3_(Embryophyta)' WHERE accession='NP_001050276.1'
UPDATE sequence SET variant='cH3_(Vertebrata)' WHERE accession='NP_001091119.1'
UPDATE sequence SET variant='cH3.1_(Mammalia)' WHERE accession='NP_001180643.1'
UPDATE sequence SET variant='cH3_(Animals)' WHERE accession='NP_001268409.1'
UPDATE sequence SET variant='cH3_(Embryophyta)' WHERE accession='NP_189372.1'
UPDATE sequence SET variant='cH3_(Animals)' WHERE accession='NP_509344.1'
UPDATE sequence SET variant='cH3.1_(Mammalia)' WHERE accession='NP_659539.1'
UPDATE sequence SET variant='cH3_(Protists)' WHERE accession='XP_001016594.3'
UPDATE sequence SET variant='cH3_(Protists)' WHERE accession='XP_001218942.1'
UPDATE sequence SET variant='cH3_(Protists)' WHERE accession='XP_002288694.1'
UPDATE sequence SET variant='cH3_(Protists)' WHERE accession='XP_002788889.1'
UPDATE sequence SET variant='cH3_(Embryophyta)' WHERE accession='XP_002977792.1'
UPDATE sequence SET variant='cH3_(Protists)' WHERE accession='XP_002999294.1'
UPDATE sequence SET variant='cH3_(Fungi)' WHERE accession='XP_460476.1'
UPDATE sequence SET variant='cH3.1_(Mammalia)' WHERE accession='XP_527254.2'
UPDATE sequence SET variant='cH3_(Fungi)' WHERE accession='XP_719887.1'
UPDATE sequence SET variant='cH3_(Protists)' WHERE accession='XP_724814.1'

In [19]:
query = "SELECT * FROM sequence "
cursor.execute(query)
df = pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])
print(df[df["accession"].isin(data_for_upd.keys())].shape)
df[df["accession"].isin(data_for_upd.keys())]

(20, 13)

,accession,variant,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,sequence,variant_under_consideration
942,CAA32434.1,cH3_(Animals),8070,None,None,7227.0,Drosophila melanogaster,Arthropoda,Insecta,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3411,NP_001027285.1,cH3_(Animals),78706960,None,None,7227.0,Drosophila melanogaster,Arthropoda,Insecta,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3421,NP_001044904.1,cH3_(Embryophyta),115441249,None,None,39947.0,Oryza sativa Japonica Group,Streptophyta,Magnoliopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRFRPGT...,None
3422,NP_001050276.1,cH3_(Embryophyta),115453351,None,None,39947.0,Oryza sativa Japonica Group,Streptophyta,Magnoliopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...,None
3439,NP_001091119.1,cH3_(Vertebrata),148234575,None,None,8355.0,Xenopus laevis,Chordata,Amphibia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3454,NP_001180643.1,cH3.1_(Mammalia),302565464,None,None,9544.0,Macaca mulatta,Chordata,Mammalia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3465,NP_001268409.1,cH3_(Animals),527498246,None,None,9031.0,Gallus gallus,Chordata,Aves,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
3586,NP_189372.1,cH3_(Embryophyta),15232146,None,None,3702.0,Arabidopsis thaliana,Streptophyta,Magnoliopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRFRPGT...,None
3603,NP_509344.1,cH3_(Animals),17567723,None,None,6239.0,Caenorhabditis elegans,Nematoda,Chromadorea,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...,None
3620,NP_659539.1,cH3.1_(Mammalia),21489955,None,None,10090.0,Mus musculus,Chordata,Mammalia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5714,XP_001016594.3,cH3_(Protists),229595561,None,None,312017.0,Tetrahymena thermophila SB210,Ciliophora,Oligohymenophorea,None,None,MARTKQTARKSTGAKAPRKQLASKAARKSAPATGGIKKPHRFRPGT...,None
5719,XP_001218942.1,cH3_(Protists),115504299,None,None,185431.0,Trypanosoma brucei brucei TREU927,Euglenozoa,Kinetoplastea,None,None,MSRTKETARTKKTITSKKSKKASKGSDAASGVKTAQRRWRPGTVAL...,None
5755,XP_002288694.1,cH3_(Protists),223998042,None,None,296543.0,Thalassiosira pseudonana CCMP1335,Bacillariophyta,Coscinodiscophyceae,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5775,XP_002788889.1,cH3_(Protists),294956322,None,None,423536.0,Perkinsus marinus ATCC 50983,Perkinsozoa,None,None,None,MARTKQTARKSTGGKAPRKQLASKAARKSTPSTGGIKKPHRYRPGT...,None
5794,XP_002977792.1,cH3_(Embryophyta),302792052,None,None,88036.0,Selaginella moellendorffii,Streptophyta,Lycopodiopsida,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...,None
5795,XP_002999294.1,cH3_(Protists),301115049,None,None,403677.0,Phytophthora infestans T30-4,Oomycota,None,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5920,XP_460476.1,cH3_(Fungi),50423783,None,None,284592.0,Debaryomyces hansenii CBS767,Ascomycota,Saccharomycetes,None,None,MARTKQTARKSTGGKAPRKQLASKAARKSAPVSGGVKKPHRYKPGT...,None
5921,XP_527254.2,cH3.1_(Mammalia),114605759,None,None,9598.0,Pan troglodytes,Chordata,Mammalia,None,None,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRYRPGT...,None
5934,XP_719887.1,cH3_(Fungi),68472183,None,None,237561.0,Candida albicans SC5314,Ascomycota,Saccharomycetes,None,None,MARTKQTARKSTGGKAPRKQLASKAARKSAPVSGGVKKPHRYKPGT...,None
5935,XP_724814.1,cH3_(Protists),82541094,None,None,5861.0,Plasmodium yoelii,Apicomplexa,Aconoidasida,None,None,MARTKQTARKSTAGKAPRKQLASKAARKSAPISAGIKKPHRYRPGT...,None

In [20]:
# Make sure data is committed to the database
conn.commit()

# DONE H4

## <span style="color:black">Change sequence variant of cH4s</span>

```python
[{'accession': 'NP_001027352.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_001032934.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_001087926.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_001131585.1',
  'variant': 'cH4_(Embryophyta)'},
 {'accession': 'NP_009563.1',
  'variant': 'cH4_(Fungi)'},
 {'accession': 'NP_180441.1',
  'variant': 'cH4_(Embryophyta)'},
 {'accession': 'NP_291074.1',
  'variant': 'cH4_(Mammalia)'},
 {'accession': 'NP_492641.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'NP_999707.1',
  'variant': 'cH4_(Animals)'},
 {'accession': 'XP_001016593.1',
  'variant': 'cH4_(Protists)'},
 {'accession': 'XP_012928609.1',
  'variant': 'cH4_(Mammalia)'},
 {'accession': 'XP_951561.1',
  'variant': 'cH4_(Protists)'}]
```

### Add nodes to cH4_(Plants): cH4_(Chlorophyta), cH4_(Embryophyta)

In [39]:
query = (
    "SELECT * FROM histone h LEFT JOIN histone_description hd "
    "ON h.description = hd.id "
    "WHERE h.parent='cH4_(Plants)'"
)
cursor.execute(query)
pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])

Empty DataFrame
Columns: [id, level, taxonomic_span, taxonomic_span_id, description, parent, id, summary, taxonomy, genes, evolution, expression, knock_out, function, sequence, localization, deposition, structure, interactions, disease, caveats, relations]
Index: []

[0 rows x 22 columns]

In [40]:
data_histone = {
    "id": "cH4_(Chlorophyta)",
    "level": "variant",
    "taxonomic_span": "Chlorophyta",
    "taxonomic_span_id": "3041",
    "description": None,
    "parent": "cH4_(Plants)",
}
cursor.execute(add_histone, data_histone)

data_histone = {
    "id": "cH4_(Embryophyta)",
    "level": "variant",
    "taxonomic_span": "Embryophyta",
    "taxonomic_span_id": "3193",
    "description": None,
    "parent": "cH4_(Plants)",
}
cursor.execute(add_histone, data_histone)

In [41]:
query = (
    "SELECT * FROM histone h LEFT JOIN histone_description hd "
    "ON h.description = hd.id "
    "WHERE h.parent='cH4_(Plants)'"
)
cursor.execute(query)
pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])

,id,level,taxonomic_span,taxonomic_span_id,description,parent,id,summary,taxonomy,genes,...,knock_out,function,sequence,localization,deposition,structure,interactions,disease,caveats,relations
0,cH4_(Chlorophyta),variant,Chlorophyta,3041,None,cH4_(Plants),None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,cH4_(Embryophyta),variant,Embryophyta,3193,None,cH4_(Plants),None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [42]:
# Make sure data is committed to the database
conn.commit()

### Update sewuences

In [43]:
data_for_upd = {
    "NP_001027352.1": "cH4_(Animals)",
    "NP_001032934.1": "cH4_(Animals)",
    "NP_001087926.1": "cH4_(Animals)",
    "NP_001131585.1": "cH4_(Embryophyta)",
    "NP_009563.1": "cH4_(Fungi)",
    "NP_180441.1": "cH4_(Embryophyta)",
    "NP_291074.1": "cH4_(Mammalia)",
    "NP_492641.1": "cH4_(Animals)",
    "NP_999707.1": "cH4_(Animals)",
    "XP_001016593.1": "cH4_(Protists)",
    "XP_012928609.1": "cH4_(Mammalia)",
    "XP_951561.1": "cH4_(Protists)",
}
len(data_for_upd.keys())

12

In [44]:
query = "SELECT * FROM sequence "
cursor.execute(query)
df = pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])
print(df[df["accession"].isin(data_for_upd.keys())].shape)
df[df["accession"].isin(data_for_upd.keys())]

(12, 13)

,accession,variant,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,sequence,variant_under_consideration
3412,NP_001027352.1,cH4_(Animals),78707094,None,None,7227.0,Drosophila melanogaster,Arthropoda,Insecta,None,None,MTGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3415,NP_001032934.1,cH4_(Animals),83745133,None,None,9031.0,Gallus gallus,Chordata,Aves,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3436,NP_001087926.1,cH4_(Animals),148228507,None,None,8355.0,Xenopus laevis,Chordata,Amphibia,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3447,NP_001131585.1,cH4,212722314,None,None,4577.0,Zea mays,Streptophyta,Magnoliopsida,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3535,NP_009563.1,cH4,6319481,None,None,559292.0,Saccharomyces cerevisiae S288C,Ascomycota,Saccharomycetes,None,None,MSGRGKGGKGLGKGGAKRHRKILRDNIQGITKPAIRRLARRGGVKR...,None
3583,NP_180441.1,cH4,15226944,None,None,3702.0,Arabidopsis thaliana,Streptophyta,Magnoliopsida,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3596,NP_291074.1,cH4,21361209,None,None,10090.0,Mus musculus,Chordata,Mammalia,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3598,NP_492641.1,cH4,17509199,None,None,6239.0,Caenorhabditis elegans,Nematoda,Chromadorea,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3645,NP_999707.1,cH4,47551061,None,None,7668.0,Strongylocentrotus purpuratus,Echinodermata,Echinoidea,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
5713,XP_001016593.1,cH4,118366755,None,None,312017.0,Tetrahymena thermophila SB210,Ciliophora,Oligohymenophorea,None,None,MAGGKGGKGMGKVGAKRHSRKSNKASIEGITKPAIRRLARRGGVKR...,None
5879,XP_012928609.1,cH4,861442511,None,None,10181.0,Heterocephalus glaber,Chordata,Mammalia,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
5944,XP_951561.1,cH4,84043542,None,None,185431.0,Trypanosoma brucei brucei TREU927,Euglenozoa,Kinetoplastea,None,None,MAKGKRVGESKGAQKRQKKVLRDNVRGITRGSIRRLARRAGVKRIS...,None

In [45]:
for a, v in data_for_upd.items():
    query = f"UPDATE sequence SET variant='{v}' WHERE accession='{a}'"
    print(query)
    cursor.execute(query)

UPDATE sequence SET variant='cH4_(Animals)' WHERE accession='NP_001027352.1'
UPDATE sequence SET variant='cH4_(Animals)' WHERE accession='NP_001032934.1'
UPDATE sequence SET variant='cH4_(Animals)' WHERE accession='NP_001087926.1'
UPDATE sequence SET variant='cH4_(Embryophyta)' WHERE accession='NP_001131585.1'
UPDATE sequence SET variant='cH4_(Fungi)' WHERE accession='NP_009563.1'
UPDATE sequence SET variant='cH4_(Embryophyta)' WHERE accession='NP_180441.1'
UPDATE sequence SET variant='cH4_(Mammalia)' WHERE accession='NP_291074.1'
UPDATE sequence SET variant='cH4_(Animals)' WHERE accession='NP_492641.1'
UPDATE sequence SET variant='cH4_(Animals)' WHERE accession='NP_999707.1'
UPDATE sequence SET variant='cH4_(Protists)' WHERE accession='XP_001016593.1'
UPDATE sequence SET variant='cH4_(Mammalia)' WHERE accession='XP_012928609.1'
UPDATE sequence SET variant='cH4_(Protists)' WHERE accession='XP_951561.1'

In [46]:
query = "SELECT * FROM sequence "
cursor.execute(query)
df = pd.DataFrame(cursor.fetchall(), columns=[i[0] for i in cursor.description])
print(df[df["accession"].isin(data_for_upd.keys())].shape)
df[df["accession"].isin(data_for_upd.keys())]

(12, 13)

,accession,variant,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,sequence,variant_under_consideration
3412,NP_001027352.1,cH4_(Animals),78707094,None,None,7227.0,Drosophila melanogaster,Arthropoda,Insecta,None,None,MTGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3415,NP_001032934.1,cH4_(Animals),83745133,None,None,9031.0,Gallus gallus,Chordata,Aves,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3436,NP_001087926.1,cH4_(Animals),148228507,None,None,8355.0,Xenopus laevis,Chordata,Amphibia,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3447,NP_001131585.1,cH4_(Embryophyta),212722314,None,None,4577.0,Zea mays,Streptophyta,Magnoliopsida,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3535,NP_009563.1,cH4_(Fungi),6319481,None,None,559292.0,Saccharomyces cerevisiae S288C,Ascomycota,Saccharomycetes,None,None,MSGRGKGGKGLGKGGAKRHRKILRDNIQGITKPAIRRLARRGGVKR...,None
3583,NP_180441.1,cH4_(Embryophyta),15226944,None,None,3702.0,Arabidopsis thaliana,Streptophyta,Magnoliopsida,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3596,NP_291074.1,cH4_(Mammalia),21361209,None,None,10090.0,Mus musculus,Chordata,Mammalia,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3598,NP_492641.1,cH4_(Animals),17509199,None,None,6239.0,Caenorhabditis elegans,Nematoda,Chromadorea,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
3645,NP_999707.1,cH4_(Animals),47551061,None,None,7668.0,Strongylocentrotus purpuratus,Echinodermata,Echinoidea,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
5713,XP_001016593.1,cH4_(Protists),118366755,None,None,312017.0,Tetrahymena thermophila SB210,Ciliophora,Oligohymenophorea,None,None,MAGGKGGKGMGKVGAKRHSRKSNKASIEGITKPAIRRLARRGGVKR...,None
5879,XP_012928609.1,cH4_(Mammalia),861442511,None,None,10181.0,Heterocephalus glaber,Chordata,Mammalia,None,None,MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKR...,None
5944,XP_951561.1,cH4_(Protists),84043542,None,None,185431.0,Trypanosoma brucei brucei TREU927,Euglenozoa,Kinetoplastea,None,None,MAKGKRVGESKGAQKRQKKVLRDNVRGITRGSIRRLARRAGVKRIS...,None

In [47]:
# Make sure data is committed to the database
conn.commit()

# Close connections

In [48]:
cursor.close()
conn.close()
tunnel.stop()